license="${mod_license}"
issueTrackerURL="https://github.com/nathanrreed/Azurum-Miner/issues/"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="logo.png"
    updateJSONURL="https://api.modrinth.com/updates/azurum-miner/forge_updates.json?neoforge=only"
    displayURL="https://github.com/nathanrreed/Azurum-Miner"
    authors="${mod_authors}"
    #credits="" #optional
    description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"